In [4]:
import os

import cv2
import numpy as np
from numpy.lib.stride_tricks import as_strided

In [6]:
image_filename = os.path.join(
    os.environ["HOME"], "dataset/NEUMetalSurfaceDefects/train/0_Crazing_4k/Cr_120.png")
image = cv2.imread(image_filename, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
if image.shape == 2:
    image = image[..., None]
assert len(image.shape) == 3

In [11]:
array = np.where(image > 10)

In [15]:
array[0], array[1], array[2]

(array([  0,   0,   0, ..., 199, 199, 199]),
 array([  0,   0,   0, ..., 199, 199, 199]),
 array([0, 1, 2, ..., 0, 1, 2]))